### ISSUE TITLE
Определить формат записи карты

### ISSUE THREAD

**Issue by igamgam97** [igamgam97/Tartarus#3]

**Comment by vahriin** [comment]
Такс... Немного о том, как хранятся данные на Mifare1k-карте:
Имеется 16 секторов, в каждом по 4 блока, в каждом по 16 байт. Каждый сектор имеет блок-trailer, обычно он последний в секторе. Trailer состоит из 3 частей: ключ А, биты доступа, ключ B.
Каждый из ключей занимает 6 байт. Первые 6 байт трейлера занимает ключ A. Затем идут 3 байта, содержащие биты доступа для каждого блока, сконфигурированные хитрым образом (до конца не разобрался). Эти биты описывают, с помощью какого ключа можно читать информацию, записанную текущем секторе, в каждом из блоков. Биты могут быть сконфигурированы таким образом, чтобы, к примеру:
1) читать и записывать с помощью ключа A (Транспортная конфингурация, такими карты выходят с завода);
2) читать с помощью ключа А, записывать с помощью ключа B (так называемая конфигурация "все читают, один пишет", используется в картах метро, например);
3) читать и записывать с помощью ключа B (привелегированная запись);
4) read-only с помощью любого ключа;
5) вообще не читать и не записывать.
На самом деле, их больше, я перечислил основные. 
К этому вернемся потом, пока описываю дальше. После байтов доступа есть целый байт пользовательских данных и 6 байт ключа B (который можно заменить пользовательскими данными).
В остальных блоках сектора можно писать любую информацию.

Но! В первом блоке записан номер карты и данные о фабрике-производителе. Вообще в имеющихся у меня на руках метках номер карты занимает 7 байт. Затем инфа о производителе. Этот блок read-only. Таким образом, имеем 3*15+2=47 блоков, что равно 752 байтам.

**Comment by vahriin** [comment]
Теперь касаемо доступа. Здесь я описываю доступ к байтам той части ключа, которая будет храниться на карте. Вне зависимости от количества этих байтов юзать будем единую систему. Итак. 
Имеются ключи A и B. Если блоки сконфигурированы как текстовые (есть еще вариант конфигурации как value, но он нам не нужен), то они поддерживают, соответственно, чтение и запись (read/write block). Теперь такая интересная штука: можно разрешить чтение с помощью обоих ключей, а запись только с помощью ключа B, а можно все завязать на ключ B. Напомню, карты требуется перезаписывать, для, допустим, удаления одного блока шифрованных данных и его замены другим. 
Первый способ нам подошел бы, если бы хранящиеся части ключа считывались бы другими устройствами, кроме нашего; нам же, напротив, нужно этого избежать. С другой стороны, это позволит нам хранить на ардуино лишь ключ A для считывания, а при создании новой записи ключ B будет генерироваться на компьютере. Большого практического смысла это не несет; от атаки посредством перезаписи карты не защищает. 
Второй способ позволяет работать лишь с ключом B. Все, что мне не нравится в этом способе - совершенно не нужный ключ А. С другой стороны, он в 2 раза снижает шанс получения ключа посредством брутфорса (так как будет использоваться только один ключ). Опять-таки, все спорно.

**Comment by vahriin** [comment]
Теперь насчет хранения самих ключей. Для их изменения и чтения тоже требуется сконфигурировать биты доступа. Здесь уже 3 варианта:
1) Всё на ключ А. С его помощью мы можем изменить ключи, прочитать биты доступа и ключ В. При этом невозможно изменить биты доступа. Этот вариант мне нравится меньше всего, так как завладев ключом А, можно получить доступ ко всей карте (изменение битов доступа в этом случае невозможно). Из плюсов - иллюзиорное разделение прав между ключами. (0 0 0)
2) Все на ключ B с возможностью изменения битов доступа. Как тестовый вариант использовать можно. В "релизном" случае не вижу смысла использовать изменяемые ключи. (0 1 1)
3) Все на ключ В. Пожалуй, лучший вариант для комбинирования со вторым вариантом доступа к данным. Конечно, всё завязано на ключ B, скомпрометировав который, мы получаем скомпрометированную часть ключа, но скомпрометировать один ключ в два раза сложнее, чем два :) (1 0 0)

**Comment by vahriin** [comment]
Что касается самих ключей - предлагаю хранить 384 бита первой части закрытого ключа на карте. Они займут ровно один сектор. Таким образом, на одну карту можно записать ключи для 15 зашифрованных ячеек (зашифрованных объектов на компьютере). Если кому-то понадобится больше (что вряд ли) - всегда есть четырехкилобайтные карты.
В качестве конфигурации битов доступа предлагаю использовать тип "Все на ключ В".
Нулевой сектор (содержащий блок с номером карты и данными фабрики) предлагаю сконфигурировать как "читаем с помощью ключа А, пишем с помощью В" и оставить пустым.

**Comment by vahriin** [comment]
Определен формат чтения/записи данных - 0 1 1
Определен формат чтения/записи трейлера в тестовой конфигурации - 0 1 1
Определен формат чтения/записи трейлера в релизной конфигурации - 1 0 0
